config/routes.rb
SearchTool::Application.routes.draw do

  resources :classifications
  resources :search_items  do
    collection do
             get 'download'
      end
    end

  root :to => 'search_items#new'

end

app/models/classification.rb
class Classification < ActiveRecord::Base
  attr_accessible :value , :search_items
  has_many :search_items
end

app/models/search_item.rb
class SearchItem < ActiveRecord::Base
  attr_accessible :name ,:file, :classification_id
  belongs_to :classification
  mount_uploader :file, SearchItemsUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  http_basic_authenticate_with :name => "quandl",:password => "quandl"
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
  # GET /classifications
  # GET /classifications.json
  def index
    @classifications = Classification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classifications }
    end
  end

  # GET /classifications/1
  # GET /classifications/1.json
  def show
    @classification = Classification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classification }
    end
  end

  # GET /classifications/new
  # GET /classifications/new.json
  def new
    @classification = Classification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classification }
    end
  end

  # GET /classifications/1/edit
  def edit
    @classification = Classification.find(params[:id])
  end

  # POST /classifications
  # POST /classifications.json
  def create
    @classification = Classification.new(params[:classification])

    respond_to do |format|
      if @classification.save
        format.html { redirect_to @classification, notice: 'Classification was successfully created.' }
        format.json { render json: @classification, status: :created, location: @classification }
      else
        format.html { render action: "new" }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /classifications/1
  # PUT /classifications/1.json
  def update
    @classification = Classification.find(params[:id])

    respond_to do |format|
      if @classification.update_attributes(params[:classification])
        format.html { redirect_to @classification, notice: 'Classification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifications/1
  # DELETE /classifications/1.json
  def destroy
    unclassified_id = Classification.find_by_value('Unclassified').id
    @classification = Classification.find(params[:id])

    SearchItem.where(classification_id: @classification.id).each do |i|
          i.classification_id = unclassified_id
          i.save
    end

    @classification.destroy

    respond_to do |format|
      format.html { redirect_to classifications_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/search_items_controller.rb
class SearchItemsController < ApplicationController
  # GET /search_items
  # GET /search_items.json


  def download


     data=[]
     @search_items=SearchItem.where(classification_id: params[:status])
     @search_items.each do |search_item|
       data << search_item.name
     end

   send_data data.join("\n"), type: "text", filename: "#{Classification.find_by_id(params[:status]).value}.txt"
    #
     #file = "search_items.txt"
     #File.open(file, "a"){ |f| f << data}
     ##f=File.new("out", "w")
     #
     ##(1..data.size).each do |i|
     ##  f.puts (data[i])
     ##  #file.write "\n"
     ## end
     #
     #send_file( file )
     ##send_file( f )
     ##send_data data, :filename => 'download.txt',:disposition => 'inline'

  end

  def index
    if params[:status].blank?
      @search_items = SearchItem.all
      @classifications = Classification.all


    else
      @search_items = SearchItem.where(classification_id: params[:status]).page(params[:page]).per(10)
      @classifications = Classification.all
    end

    @title = Classification.find(params[:status]).value


    #redirect_to search_items_path
    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render json: @search_items }
    #end
  end

  # GET /search_items/1
  # GET /search_items/1.json
  def show
    @search_item = SearchItem.find(params[:id])
    #@search_items = SearchItem.paginate(:page=>params[:page], :per_page => 5, :order => 'created_at DESC')

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search_item }
    end
  end

  ## Show All Rows in the Database

  def show_all
    @search_item = SearchItem.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search_item }
    end
  end

  def show_good
    @search_item = SearchItem.where(classification_id: 15)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search_item }
    end
  end

  # GET /search_items/new
  # GET /search_items/new.json
  def new
    @search_item = SearchItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search_item }
    end
  end

  # GET /search_items/1/edit
  def edit
    @search_item = SearchItem.find(params[:id])
  end

  # POST /search_items
  # POST /search_items.json


  # @param [Object] str
  def exist_check (str)
    temp_search_items=SearchItem.all
    temp_search_items.each do  |t|
      if t.name == str
        return true
      end
    end
    return false
  end

  def create

    uploaded_file = params[:search_item][:file]
    file_content = uploaded_file.read.split("\n")

    file_content.each do |line|

      if ! exist_check (line.strip)
        @search_item = SearchItem.new(params[:search_item])
        @search_item.name = line.strip
        @search_item.classification_id=Classification.find_by_value("Unclassified").id
        @search_item.save
      end

    end
    respond_to do |format|

      #format.html { redirect_to @search_item, notice: 'Search items were successfully created.' }
      format.html { redirect_to search_items_path(:status=> Classification.find_by_value("Unclassified").id), notice: 'Search items were successfully created.' }
      format.json { render json: @search_item, status: :created, location: @search_item }
    #  #else
    #  #  format.html { render action: "new" }
    #  #  format.json { render json: @search_item.errors, status: :unprocessable_entity }
    #  #end
    end
  end

  # PUT /search_items/:id
  def update
    @search_item = SearchItem.find(params[:id])
    @search_item.classification_id = params[:search_item][:classification_id]
    @search_item.save


    redirect_to search_items_path(:status=>params[:search_item][:status])

    #redirect_to search_items_path

    #if(@search_item.classification_id ==15)

    #elsif (@search_item.classification_id ==16)
    #  redirect_to search_items_path(:status=>16)
    #else
    #  redirect_to search_items_path(:status=>17)
    #end


    #respond_to do |format|
    #  if @search_item.update_attributes(params[:search_item])
    #    format.html { redirect_to @search_item, notice: 'Search item was successfully updated.' }
    #    format.json { head :no_content }
    #  else
    #    format.html { render action: "edit" }
    #    format.json { render json: @search_item.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # DELETE /search_items/1
  # DELETE /search_items/1.json
  def destroy
    @search_item = SearchItem.find(params[:id])
    temp=@search_item
    @search_item.destroy

    respond_to do |format|
      format.html { redirect_to search_items_path(:status=> Classification.find_by_value(temp.classification.value).id) }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/helpers/search_items_helper.rb
module SearchItemsHelper
end

app/views/classifications/_form.html.erb
<%= form_for(@classification) do |f| %>
  <% if @classification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classification.errors.count, "error") %> prohibited this classification from being saved:</h2>

      <ul>
      <% @classification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-small" %>
  </div>
<% end %>

app/views/classifications/edit.html.erb
<h1>Editing classification</h1>

<%= render 'form' %>

<%= link_to 'Show', @classification %> |
<%= link_to 'Back', classifications_path %>

app/views/classifications/index.html.erb
<h1>Classification List</h1>

<table class="table table-bordered table-hover">
  <tr>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @classifications.each do |classification| %>

      <%if classification.value == "Unclassified" %>
          <tr>
            <td><%=link_to classification.value, search_items_path(:status=>Classification.find_by_value(classification.value).id) %></td>
            <td><%= link_to 'Edit', edit_classification_path(classification), :class=>"btn" %></td>
          </tr>
      <%else%>

      <tr>
        <td><%= link_to classification.value, search_items_path(:status=>Classification.find_by_value(classification.value).id) %></td>
        <td><%= link_to 'Edit', edit_classification_path(classification),:class=>"btn" %></td>
        <td><%= link_to 'Delete', classification, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>
      </tr>
      <% end %>
<% end %>
</table>

<br />

<%= link_to 'Add New Classification', new_classification_path,:class=>"btn" %>

app/views/classifications/new.html.erb
<h1>Add New Classification</h1>

<%= render 'form' %>

<%= link_to 'Back', classifications_path,:class=>"btn" %>

app/views/classifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @classification.value %>
</p>


<%= link_to 'Edit', edit_classification_path(@classification) %> |
<%= link_to 'Back', classifications_path %>

app/views/classifications/show_all.erb
<h1>Show ALL Data </h1>

<table>
  <tr>
    <th>Search Key:</th>
    <th>Value:</th>
    <th></th>
  </tr>

  <% SearchItem.all.each do |search_item|%>
      <tr>
        <td><%=  search_item.name %></td>
        <td><%=search_item.classification.value %></td>

      </tr>
  <% end %>
</table>

<%=link_to 'Back', search_items_path %>

app/views/classifications/show_good.erb
<h1>Show Good Data Status</h1>

<table>
  <tr>
    <th>Search Key:</th>
    <th>Value:</th>
    <th></th>
  </tr>

  <% SearchItem.where(classification_id: 15).each do |search_item|%>
      <tr>
        <td><%=  search_item.name %></td>
        <td><%=search_item.classification.value %></td>

      </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SearchTool</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
        <ul class="nav">
          <li><%= link_to "Classification", classifications_path,:class=>"btn" %></li>
          <li><%= link_to "Search Item", search_items_path(:status=> Classification.find_by_value("Unclassified").id),:class=>"btn"%></li>
          <li><%= link_to 'Upload Data', new_search_item_path,:class=>"btn" %></li>
          <li><%= link_to 'Download Data', download_search_items_path(:status=>params[:status]),:class=>"btn" %></li>
        </ul>
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/search_items/_form.html.erb
<%= form_for @search_item, html: {multipart: true} do |f| %>
  <% if @search_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search_item.errors.count, "error") %> prohibited this search_item from being saved:</h2>

      <ul>
      <% @search_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit "Upload File",:class=>"btn btn-small" %>
  </div>
<% end %>

app/views/search_items/edit.html.erb
<h1>Editing search_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @search_item %> |
<%= link_to 'Back', search_items_path %>

app/views/search_items/form_2.erb
<%= form_for @classifications, html: {multipart: true} do |f| %>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/search_items/index.html.erb
<h1><%=@title  %></h1>
<%@classifications.each do |classification|%>
    &nbsp<%= link_to classification.value, search_items_path(status: classification.id),:class => "btn"%>
<%end%>

<br><br><br>

<table class="table table-bordered table-hover">
  <tr>
    <th>Search Term</th>
    <th></th>
  </tr>


<% @search_items.each do |search_item| %>
  <tr>
    <td>&nbsp<%= link_to search_item.name,"http://www.quandl.com/search/#{search_item.name}", :target => "_blank" %></td>

      <% @classifications.each do |classification| %>
        <%= form_for search_item do |f|%>
            <%= f.hidden_field :classification_id, :value => classification.id %>
            <%= hidden_field_tag 'selected', 'none'  %>
            <%= f.hidden_field :status, :value => params[:status] %>
       <td><%= f.submit classification.value, :class=>"btn btn-small"%></td>
      <% end %>
    <% end %>

    <td>&nbsp<%= link_to 'Delete', search_item, method: :delete, data: { confirm: 'Are you sure?' } ,
                         :class=>"btn btn-danger"%></td>

  </tr>
<% end %>

</table>

<%= paginate @search_items %>

<br />

app/views/search_items/new.html.erb
<h1>Upload Search Keywords (Text File)</h1>

<%= render 'form' %>

<%= link_to 'Back', search_items_path(:status=> Classification.find_by_value("Unclassified").id),:class=>"btn" %>

app/views/search_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @search_item.name %>

</p>


<%= link_to 'Edit', edit_search_item_path(@search_item) %> |
<%= link_to 'Back', search_items_path(:status=> Classification.find_by_value("Good").id) %>

app/views/search_items/show_bad.erb
<h1>Show Bad Data Status</h1>

<table>
  <tr>
    <th>Search Key:</th>
    <th>Value:</th>
    <th></th>
  </tr>

  <% SearchItem.where(classification_id: 16).each do |search_item|%>
      <tr>
        <td><%=search_item.name %></td>
        <td><%=search_item.classification.value %></td>

      </tr>
  <% end %>
</table>

<%=link_to 'Back', search_items_path %>

app/views/search_items/show_good.erb
<h1>Show Good Data Status</h1>

<table>
  <tr>
    <th>Search Key:</th>
    <th>Value:</th>
    <th></th>
  </tr>

  <% SearchItem.where(classification_id: 15).each do |search_item|%>
      <tr>
        <td><%=search_item.name %></td>
        <td><%=search_item.classification.value %></td>

      </tr>
  <% end %>
</table>
<%=link_to 'Back', search_items_path %>

app/views/search_items/update_good_data.erb
<h1>Show ALL Data </h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% SearchItem.all.each do |search_item|%>
      <tr>
        <td><b>Search Key:</b> <%=  search_item.name %></td>
        <td><b>Classification:</b> <%  cID=search_item.classification_id%> <%=  Classification.find(cID).value %></td>
      </tr>
  <% end %>
</table>